/**
 * Hacker News
 * <p>Hacker News API</p> 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item { 
    by: string;
    id?: number;
    kids?: number;
    parent?: number;
    parts?: number;
    score?: number;
    text?: string;
    time?: number;
    title?: string;
    type?: string;
    url?: string;
}